#!/bin/bash

echo Script HT

echo BLOCS GAUCHE

#echo Voie 0
#./ht --serial 1 --hton --ch 0 --hv 2000
#echo Voie 1
#./ht --serial 1 --hton --ch 1 --hv 1000
#echo Voie 2
#./ht --serial 1 --hton --ch 2 --hv 1000
#echo Voie 3
#./ht --serial 1 --hton --ch 3 --hv 960
#echo Voie 4
#./ht --serial 1 --hton --ch 4 --hv 1000
#echo Voie 5
#./ht --serial 1 --hton --ch 5 --hv 1000
#echo Voie 6
#./ht --serial 1 --hton --ch 6 --hv 1000
#echo Voie 7
#./ht --serial 1 --hton --ch 7 --hv 1000
#echo Voie 8
#./ht --serial 1 --hton --ch 8 --hv 1000
#echo Voie 9
#./ht --serial 1 --hton --ch 9 --hv 980
#echo Voie 10
#./ht --serial 1 --hton --ch 10 --hv 1000


echo BLOCS DROITE

echo Voie 0ls

./ht --serial 2 --hton --ch 0 --hv 2000
echo Voie 1
./ht --serial 2 --hton --ch 1 --hv 1000
echo Voie 2
./ht --serial 2 --hton --ch 2 --hv 975
echo Voie 3
./ht --serial 2 --hton --ch 3 --hv 990
echo Voie 4
./ht --serial 2 --hton --ch 4 --hv 1000
echo Voie 5
./ht --serial 2 --hton --ch 5 --hv 1000
echo Voie 6
./ht --serial 2 --hton --ch 6 --hv 1000
echo Voie 7
./ht --serial 2 --hton --ch 7 --hv 1000
echo Voie 8
./ht --serial 2 --hton --ch 8 --hv 1000
echo Voie 9
./ht --serial 2 --hton --ch 9 --hv 975
echo Voie 10
./ht --serial 2 --hton --ch 10 --hv 1000




#echo Voie 11
#./ht --serial 2 --hton --ch 11 --hv 500
#echo Voie 12
#./ht --serial 2 --hton --ch 12 --hv 500
#echo Voie 13
#./ht --serial 2 --hton --ch 13 --hv 500
#echo Voie 14
#./ht --serial 2 --hton --ch 14 --hv 500
#echo Voie 15
#./ht --serial 2 --hton --ch 15 --hv 500
 

